# Generated by Django 5.1.2 on 2024-10-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='variante_precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
