# Generated by Django 5.1.2 on 2024-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variante_variante_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='variante_value',
            field=models.CharField(choices=[('Estandar', 'Estandar')], max_length=100),
        ),
    ]
