# Generated by Django 5.1.2 on 2024-10-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cartitem_variations'),
        ('store', '0004_alter_variante_variante_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variantes',
            field=models.ManyToManyField(blank=True, to='store.variante'),
        ),
    ]
