# Generated by Django 5.1.2 on 2024-10-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('cat_imagen', models.ImageField(blank=True, upload_to='photos/categories')),
            ],
        ),
    ]
