# Generated by Django 5.1.2 on 2024-11-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
