# Generated by Django 5.1.2 on 2024-11-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_pedido_metodo_envio'),
        ('store', '0005_alter_variante_variante_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_producto',
            name='variante',
        ),
        migrations.AddField(
            model_name='pedido_producto',
            name='variantes',
            field=models.ManyToManyField(blank=True, to='store.variante'),
        ),
    ]
