# Generated by Django 5.1.2 on 2024-11-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_pedido_producto_variante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='created_at',
        ),
    ]
